feat: add limit exceeded error [PHX-2493]
contentful/contentful-merge pull request #363
Opened 2023-09-01 10:32 UTC by mayakarabula

2023-09-04 08:43 UTC, damienxy requested changes
The error is pretty but it's not working yet :-)

2023-09-04 08:43 UTC, damienxy commented on src/engine/apply-changeset/tasks/apply-compute-ids-task.ts
> +      const exceedsLimits = changegestExceedLimits(context)
There's a typo

2023-09-04 08:43 UTC, damienxy commented on src/engine/errors.ts
> +export class LimitsExceededForApplyError extends ContentfulError {
Should we give [the other LimitsExceeded error](https://github.com/contentful/contentful-merge/pull/363/files#diff-47876649927a4e73623e91b40e9227cac585dba2c76453af7e56cd181d3d9d3eR17) also a more explicit name now that we have two?

2023-09-04 08:43 UTC, damienxy commented on src/engine/apply-changeset/index.ts
> +              applyLoadChangesetTask(),
This will not throw an error, as it counts the changeset items before the changeset is loaded

2023-09-04 08:43 UTC, damienxy commented on src/engine/apply-changeset/tasks/apply-compute-ids-task.ts
> +}
This is unused

2023-09-04 08:43 UTC, damienxy commented on src/engine/errors.ts
> +      limit: context.limit,
Currently there is no limit set. 
It should be set [here](https://github.com/contentful/contentful-merge/blob/06e5e2832f0e7c5a81f6fd1d86a9662033d1a3bd/src/commands/apply/index.ts#L66) (and not coming from a flag).

2023-09-07 09:08 UTC, damienxy commented on src/commands/apply/index.ts
> +      limit: 200,
Why 200?

2023-09-07 09:10 UTC, mayakarabula commented on src/commands/apply/index.ts
> +      limit: 200,
a typo sorry!

2023-09-07 14:13 UTC, damienxy approved these changes

2023-09-08 09:46 UTC, merged