feat: sort entries by references before add
contentful/contentful-merge pull request #913
Opened 2024-08-12 13:43 UTC by Cyberxon

In order to avoid errors when creating entries using the contentful-merge cli, we introduced a sort on the Add task where we make sure we order the Add changeset in a way that the referenced entries come before the entries they are referenced in.

2024-08-12 15:44 UTC, marcolink approved these changes
Looking good 👏 
Maybe we should mention in code or the PR description that this logic is "inspired" by the import CLI.

2024-08-12 15:44 UTC, marcolink commented on src/engine/utils/sort-entries-by-reference.ts
> +export default function sortEntries(entries: AddedChangesetItem[]): AddedChangesetItem[] {
Should we call this function also `sortEntriesByReference`?

2024-08-13 15:21 UTC, screamcha requested changes
In general I prefer using native JS methods, especially if it's straightforward, because of the following reasons:
* it improves code readability - it's safer to assume that more people are familiar with native JS methods than methods from 3rd party lib
* it reduces dependency on the 3rd party lib
* in most of the cases it doesn't bring any value as the language provides decent alternatives
I'd ask you to refrain from such methods as `map`, `filter`, `get` etc. from lodash where they don't bring more to the table compared to the native methods.
I will be happy to discuss it further, there's a high chance I'm missing something so feel free to let me know :)

2024-08-13 15:21 UTC, screamcha commented on src/engine/utils/sort-entries-by-reference.ts
> +    const entryIndex = entries.indexOf(entry)
You can get the index of an element from function parameters, it is the second parameter (both in lodash and native methods).

2024-08-13 15:21 UTC, screamcha commented on src/engine/utils/sort-entries-by-reference.ts
> +      field = values(field)[0]
Could we use `Object.values` here instead?

2024-08-13 15:21 UTC, screamcha commented on src/engine/utils/sort-entries-by-reference.ts
> +  const id = get(field, 'sys.id')
```suggestion
  const { id } = field.sys
```

2024-08-13 15:21 UTC, screamcha commented on src/engine/utils/sort-entries-by-reference.ts
> +      linkIndexes: filter(flatten(rawLinks), (index: number) => index >= 0) as number[],
[Array.prototype.flat()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat) should do the same trick as `flatten`. 
[Array.prototype.filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) should do the same trick as `filter`.

2024-08-14 11:51 UTC, screamcha approved these changes
🥇

2024-08-14 11:56 UTC, merged